# .github/workflows/publish.yml
name: Deploy to Glitch
permissions: write-all


on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and Push    
    steps:
      - uses: actions/checkout@v4
      - name: repo-sync
        uses: wei/git-sync@v1
        env:
          SOURCE_REPO: "https://github.com/kemo-1/beam_party.git"
          SOURCE_BRANCH: "server"
          DESTINATION_REPO: ${{ secrets.GLITCH_GIT_URL }}
          DESTINATION_BRANCH: "master"
        with:
          args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH

