name: Deploy Frontend

on:
  workflow_dispatch:



jobs:
  build:
    name: Build the project 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: install gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.3"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: cd lustre && gleam deps download 
        
      - name: Build project
        run: cd lustre && npm install --force && npm run build
        
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_NAME }}
          directory: ./lustre/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
